name: Deploy Medusa to EC2

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH to connect to your EC2 instance
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 3: Install dependencies on the EC2 instance
      - name: Install dependencies on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_Public_IP> '
            sudo apt update &&
            sudo apt install -y nodejs npm postgresql postgresql-contrib &&
            npm install -g @medusajs/medusa-cli
          '

      # Step 4: Copy the Medusa project to the EC2 instance
      - name: Copy Medusa project to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r . ubuntu@<EC2_Public_IP>:/var/www/medusa/

      # Step 5: Set up PostgreSQL and run Medusa on EC2
      - name: Set up PostgreSQL and run Medusa
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_Public_IP> '
            sudo systemctl start postgresql &&
            sudo -u postgres psql -c "CREATE USER dinesh WITH PASSWORD '\''dineshpm15'\'';" &&
            sudo -u postgres psql -c "ALTER USER dinesh CREATEDB;" &&
            sudo -u postgres psql -c "CREATE DATABASE medusa1_db OWNER dinesh;" &&
            cd /var/www/medusa &&
            echo "DATABASE_URL=postgres://dinesh:dineshpm15@localhost:5432/medusa1_db" > .env &&
            medusa develop
          '
